BulkyBookWeb/Areas/Admin/Controllers/CoverTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BulkyBook.DataAccess;
using BulkyBook.Models.Models;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Authorization;
using BulkyBook.Utility;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;


        public CoverTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        //Get All
        public IActionResult Index() {

            IEnumerable<CoverType> coverTypes = _unitOfWork.CoverType.GetAll();
            return View(coverTypes);    
        }

        //Create New - Form
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj) {
      
            // Add validation 
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Created Successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            /** Find all categories can be done in many ways as: 
             * _db.categories.single<u=>u.Id=id> Or 
             * _db.categories.SignleOrDefault(id)**/
            var coverTypesList = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (coverTypesList == null)
            {
                return NotFound();
            }
            return View(coverTypesList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            
         
            // Add validation 
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            /** Find all categories can be done in many ways as: 
             * _db.categories.single<u=>u.Id=id> Or 
             * _db.categories.SignleOrDefault(id)**/
            var coverTypesList = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (coverTypesList == null)
            {
                return NotFound();
            }
            return View(coverTypesList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CoverType obj)
        {
            _unitOfWork.CoverType.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Deleted Successfully!";
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverTypes/Create.cshtml
@model BulkyBook.Models.Models.CoverType

@{
    ViewData["Title"] = "Create";
}

<br /><br />

<h4>Cover Type</h4>
<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-action="Create">
        <div class="border p-3 mt-4">
                <div class="row pb-2">
                    <h5 class="text-primary">Create New Cover Type</h5>
                    <hr />
                 </div>
            
          <div class="mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            <a asp-area="Admin" asp-controller="CoverTypes" asp-action="Index" class="btn btn-secondary"> Go Back to the List</a>
            </div>
        </div>
</form>
       
<!-- Client Side Validation-->
@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
}

BulkyBookWeb/Areas/Admin/Views/CoverTypes/Delete.cshtml
@model BulkyBook.Models.Models.CoverType

@{
    ViewData["Title"] = "Delete";
}


<br /><br />
<h5>Are you sure you want to delete this?</h5>
<div class="border p-3 mt-4">
    <h4>Cover Type</h4>
    <hr />
   
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

BulkyBookWeb/Areas/Admin/Views/CoverTypes/Details.cshtml
@model BulkyBook.Models.Models.CoverType

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CoverType</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BulkyBookWeb/Areas/Admin/Views/CoverTypes/Edit.cshtml
@model BulkyBook.Models.Models.CoverType

@{
    ViewData["Title"] = "Edit";
}

<br /><br />

<h4>Cover Type</h4>
<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h5 class="text-primary">Edit Cover Type</h5>
            <hr />
        </div>

          <input type="hidden" asp-for="Id" />
         <div class="mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
         </div>
         <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Back to the List</a>
          </div>
      
    </div>

</form>

BulkyBookWeb/Areas/Admin/Views/CoverTypes/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<h1>Cover Types List</h1>
<br />

<a class="btn btn-primary" asp-area="Admin" asp-controller="CoverTypes" asp-action="Create"><i class="bi bi-plus"></i> &nbsp;Create New Cover Type</a>
<br />
<br />
<table class="table table-bordered table-striped" style="width=100%">
    <thead>
        <tr>
            <th>Cover Type Name</th>
            <th></th>
        </tr>

    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td style="width=50%"> @obj.Name</td>
                <td style="width=4%">
                    <div class="w-75 btn-group" role="group">
                        <a class="btn btn-primary mx-2" asp-controller="CoverTypes" asp-action="Edit" asp-route-id="@obj.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                        <a class="btn btn-danger mx-0" asp-controller="CoverTypes" asp-action="Delete" asp-route-id="@obj.Id"><i class="bi bi-trash"></i> Delete</a>
                    </div>



                </td>
            </tr>
        }

    </tbody>
</table>