BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
   
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {

        /*
         * DI
         * Here we created an object from the previously create class ApplicationDbContext
         */
        private readonly IUnitOfWork _unitOfWork;

        /*
         * Create a constroctor to assign an object to the above
         * we don't need to call the constructor as new ApplicationDbContext() and pass our values to connect
         * Because we already created our connection in Program.cs
         * And we just have to call the tables directly in two steps"
         *  1. Create an object of the class 
         *  2. Assign that object in the constructor
         */
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            //var objCategory = _db.categories.ToList(); -> Return the list
            /*IEnumerable
             * supports a simple iteration over a non-generic collection.
             */
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //Check for equal values ! (this is server side )
            if (obj.Name.Trim() == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Custom", "Name And Display Order Cannot be Matching");
            }
            // Add validation 
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Created Successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            /** Find all categories can be done in many ways as: 
             * _db.categories.single<u=>u.Id=id> Or 
             * _db.categories.SignleOrDefault(id)**/
            var categoryList = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (categoryList == null)
            {
                return NotFound();
            }
            return View(categoryList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            //Check for equal values ! (this is server side )
            if (obj.Name.Trim() == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Custom", "Name And Display Order Cannot be Matching");
            }
            // Add validation 
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            /** Find all categories can be done in many ways as: 
             * _db.categories.single<u=>u.Id=id> Or 
             * _db.categories.SignleOrDefault(id)**/
            var categoryList = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (categoryList == null)
            {
                return NotFound();
            }
            return View(categoryList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category obj)
        {
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Deleted Successfully!";
            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        // Return a View with dataTable data
        public IActionResult Index()
        {
            return View();
        }

        //Return Form View (Insert new if Id = 0 | update if the company exist)
        public IActionResult Upsert(int? id)
        {
            Company companyObj = new();

            if (id == null || id == 0)
            {
                return View(companyObj);
            }
            else { 
                companyObj = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);
                return View(companyObj);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company companyObj)
        {

            if (ModelState.IsValid)
            {

                if (companyObj.Id == 0)
                {

                    _unitOfWork.Company.Add(companyObj);

                }
                else
                {
                    _unitOfWork.Company.Update(companyObj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Comapnt created successfully";
                return RedirectToAction("Index");

            }
            return View(companyObj);
        }
        // Get all companies using DataTable
        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var companiesList = _unitOfWork.Company.GetAll();
            return Json(new { data = companiesList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Company.GetFirstOrDefault(u=>u.Id ==id);
            if(obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
              
            _unitOfWork.Company.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Company Deleted Successfully!" });
            
        }
        #endregion
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BulkyBook.DataAccess;
using BulkyBook.Models.Models;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using BulkyBook.Utility;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductsController : Controller
    {
        /* 
         * IUnitOfWork have all the repositories objects + Save()
         */
        private readonly IUnitOfWork _unitOfWork;
        /*
         * IWebHostEnvironment:
         * Provides information about the web hosting environment an application is running in. As:
         *      Gets or sets the absolute path to the directory that contains the web-servable application content
         *      files. This defaults to the 'wwwroot' subfolder.
         */
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnv)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = webHostEnv;
        }

        //Get All
        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypesList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            /*
             * Insert new
             */
            if (id == null || id == 0)
            {
                
                return View(productVM);
            }
            /*
            * Else Update
            */
            else
            {
                productVM.Product = _unitOfWork.Products.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
            }
            
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;

                }
                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Products.Add(obj.Product);
                }
                else
                {
                    _unitOfWork.Products.Update(obj.Product);
                }
                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }



        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var productsList = _unitOfWork.Products.GetAll(includeProperties: "Category,CoverType");
            return Json(new { data = productsList });

        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Products.GetFirstOrDefault(u=>u.Id == id);
            if(obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Products.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted successfully" });    

        }
        #endregion
    }
}

BulkyBookWeb/Areas/Customer/Controllers/CartController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models;
using BulkyBook.Models.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
      
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartVM shoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            shoppingCartVM = new ShoppingCartVM
            {
                shoppingCartList = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product"),
                orderHeader = new ()

            };
            // We cannot get the order total directly becasue of the Specal prices we have
            /*orderTotal -> Sum(Price*count) of All items in shoppingCart
             * Example:
             * Book1 
             *          price for one book to 50 Books -> 30$
             *          price for 51 to 100 books -> 25$
             *          price for more than 100 books -> 20$
             * Book2
             *          price for one book to 50 Books -> 50$
             *          price for 51 to 100 books -> 45$
             *          price for more than 100 books -> 40$
             *          
             * if the user added 3 books of Book1 -> Count = 3
             * price is 3*30$ = 90$
             * If the user added 55 books of Book2 -> Count 55
             * price is 55*45$ = 2475$
             * 
             * OrderTotal is 90$ + 2475$ = 2565$
             */

            foreach(var item in shoppingCartVM.shoppingCartList)
            {
                item.Price = GetPriceBasedOnQuantity(item);
                shoppingCartVM.orderHeader.OrderTotal += (item.Price * item.Count);
            }


            return View(shoppingCartVM);
        }

        public IActionResult Plus (int cartItemId)
        {
            // 1. get the item from DB (ShoppingCart table)
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(u=>u.Id == cartItemId);
            cartFromDb.Count += 1;
            _unitOfWork.ShoppingCart.Update(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minuse(int cartItemId)
        {
            // 1. get the item from DB (ShoppingCart table)
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartItemId);
            if(cartFromDb.Count <= 1)
            {
                //Remove
                _unitOfWork.ShoppingCart.Remove(cartFromDb);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                cartFromDb.Count -= 1;
            }
            
            _unitOfWork.ShoppingCart.Update(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Remove(int cartItemId)
        {
            // 1. get the item from DB (ShoppingCart table)
            ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartItemId);

            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Summary()
        {
            return View();
        }

        /* in our application 
         * when user order one to 50 books -> price
         * when user order 51 - 100 books -> price 50
         * when user order more than 100 books -> price100
         */

        /*
         * if(count<=50) -> return price
         * elseif(count<=100)-> return price50
         * elseif(count>100)-> return proce100
         */
        public double GetPriceBasedOnQuantity(ShoppingCart shoppingCart)
        {
            if (shoppingCart.Count <= 50)
            {
                return shoppingCart.Product.Price;
            }
            else 
            {
                if (shoppingCart.Count <= 100) {
                    return shoppingCart.Product.Price50;
                }
                else
                {
                    return shoppingCart.Product.Price100;
                }
                    
            }
        }
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootsWatchThem.css" />
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

</head>

<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Bulky Book</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                                Home                      
                            </a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white;">Content Managment</a>

                               <div class="dropdown-menu">
                                    <a class="nav-link" asp-area="Admin" asp-controller="CoverTypes" asp-action="Index">Cover Types</a>
                                    <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Products" asp-action="Index">Product</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                               </div>
                       </li>
                       }
                       <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">
                               <i class="bg-info bi-cart">&asymp; (0)</i>                     
                            </a>
                        </li>   



                    </ul>
                
                       
                   
                    
                </div>
            </div>
  
        <partial name="_LoginPartial"></partial>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">     
            @RenderBody()
            <partial name="_Notifications"></partial>
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/q11zrvapg165ds10i8y65gf3px35fuxwt2fqsry65xec3h7g/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

BulkyBookWeb/Views/Shared/_Notifications.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        // Display a success toast, with a title
        toastr.success('@TempData["success"]');
    </script>
    
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        // Display a success toast, with a title
        toastr.error('@TempData["error"]');
    </script>
}